### PR TITLE
Correct broken hyperlinks in README.rst

### PR DESCRIPTION
**Pull request by ridamadara**

### CODE REVIEW

**Comment by jelmer** [comment]
Please keep this URLs relative - they shouldn't go to GitHub when dulwich' README is displayed elsewhere, and if you're viewing them in another branch or an old revision it shouldn't take you back to the version of AUTHORS or CONTRIBUTING in master.

**Review by jelmer — CHANGES_REQUESTED** [review]
Please keep this URLs relative - they shouldn't go to GitHub when dulwich' README is displayed elsewhere, and if you're viewing them in another branch it shouldn't take you back to master.

**Comment by DJJo14** [comment]
Can you also update the docs url from https://www.dulwich.io/docs/ to https://www.dulwich.io/apidocs which one is more up to date.

**Comment by jelmer** [comment]
This seems to have stalled, so I'll close it - feel free to open if you're still interested in working on it.

**Pull request closed without merging**
