### PR TITLE
Fuzzing Improvements

### PR DESCRIPTION
**Pull request by DaveLak**
As a follow-up to #1304, this PR introduces additional fuzz targets, fuzz test dictionaries, and `fuzzing/fuzz-targets/test_utils.py` which includes test utilities to help DRY fuzzing test code. 

The changes here should increase fuzzing coverage from ~2% to ~17% based on the results of my local testing.

The commit messages in this PR should describe the specific changes, but the most significant information detailed below:

## New Fuzz Targets

**fuzzing/fuzz-targets/fuzz_bundle.py**
- Tests the `Bundle` related functionality using fuzzer provided data.
- This test is based on [`test_bundle.py`](https://github.com/jelmer/dulwich/blob/9d13065fab6bdc0251d25bda79bb013d01f42f24/tests/test_bundle.py), the unit test of the same functionality.

**fuzzing/fuzz-targets/fuzz_object_store.py**
- Tests the `Blob`, `Tree`, and `Commit` classes using fuzzer provided data.
- This test is based on the example code in the [Object Store tutorial](https://www.dulwich.io/docs/tutorial/object-store.html), `fuzz_object_store.py` uses a `MemoryRepo` to avoid disk IO where possible, in the interest of test execution efficiency.

**fuzzing/fuzz-targets/fuzz_repo.py**

- Tests basic functionality of the `Repo` class.
- This test must perform actual disk IO to effectively test all functionality, so it is somewhat slow compared to other fuzz targets in this repo. There might be ways to improve this, but as of this PR it works well enough.

## `fuzzing/fuzz-targets/test_utils.py`

- Adds a `EnhancedFuzzedDataProvider` class that extends `atheris.FuzzedDataProvider` to abstract some common use-cases into DRY method calls.
- The `is_expected_error` helper function was extracted from `fuzz_configfile.py`  into this dedicated test utility file so it can be reused by other fuzz harnesses in `fuzz-targets/`.
  - Also renamed and better documented the `is_expected_error` function now that it is shared.

## Other Notes

I've tested all of the changes proposed here extensively in my local environment. They are working well enough that I feel they are a net value add to the fuzz test suite, but **these tests can likely be further optimized to improve coverage and efficiency**. I plan to keep an eye on their performance and further optimize the tests & supporting code as needed.

### CODE REVIEW

**Review by jelmer — CHANGES_REQUESTED** [review]
Changes look good, but please "ruff format ." the source code

**Comment by DaveLak** [comment]
> please "ruff format ." the source code

Done. Sorry about that, I've been running `ruff format fuzzing/fuzz-targets` regularly, but it seems I've been using a globally installed version of Ruff. I ran `make fix` on 3899518435825d0db2741c871639287bc8ea42ce and that seems to have done the trick.

**Comment by jelmer** [comment]
Ah, sorry - I was just going on the github action output. Fix pushed to master now for those other files. Please rebase and retry?

**Comment by DaveLak** [comment]
> Please rebase and retry

Done. My changes in `fuzzing/` are still passing `ruff check .`, but it looks like #1312 missed a few files unrelated to this PR.

After running `make reformat` I see:

```shell
❯ git status
On branch fuzzing-improvements
Your branch is up to date with 'origin/fuzzing-improvements'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   dulwich/config.py
        modified:   tests/test_client.py
        modified:   tests/test_refs.py
```

The diff:

```diff
diff --git a/dulwich/config.py b/dulwich/config.py
index c0a3de11..0d7a205a 100644
--- a/dulwich/config.py
+++ b/dulwich/config.py
@@ -175,12 +175,12 @@ class Config:
         raise NotImplementedError(self.get_multivar)
 
     @overload
-    def get_boolean(
-        self, section: SectionLike, name: NameLike, default: bool
-    ) -> bool: ...
+    def get_boolean(self, section: SectionLike, name: NameLike, default: bool) -> bool:
+        ...
 
     @overload
-    def get_boolean(self, section: SectionLike, name: NameLike) -> Optional[bool]: ...
+    def get_boolean(self, section: SectionLike, name: NameLike) -> Optional[bool]:
+        ...
 
     def get_boolean(
         self, section: SectionLike, name: NameLike, default: Optional[bool] = None
diff --git a/tests/test_client.py b/tests/test_client.py
index d219bce0..4e8484b1 100644
--- a/tests/test_client.py
+++ b/tests/test_client.py
@@ -772,9 +772,9 @@ class SSHGitClientTests(TestCase):
         )
 
     def test_alternative_command_path_spaces(self):
-        self.client.alternative_paths[b"upload-pack"] = (
-            b"/usr/lib/git/git-upload-pack -ibla"
-        )
+        self.client.alternative_paths[
+            b"upload-pack"
+        ] = b"/usr/lib/git/git-upload-pack -ibla"
         self.assertEqual(
             b"/usr/lib/git/git-upload-pack -ibla",
             self.client._get_cmd_path(b"upload-pack"),
diff --git a/tests/test_refs.py b/tests/test_refs.py
index 572be9d8..7529d775 100644
--- a/tests/test_refs.py
+++ b/tests/test_refs.py
@@ -316,9 +316,9 @@ class RefsContainerTests:
         self.assertNotIn(b"refs/tags/refs-0.2", self._refs)
 
     def test_import_refs_name(self):
-        self._refs[b"refs/remotes/origin/other"] = (
-            b"48d01bd4b77fed026b154d16493e5deab78f02ec"
-        )
+        self._refs[
+            b"refs/remotes/origin/other"
+        ] = b"48d01bd4b77fed026b154d16493e5deab78f02ec"
         self._refs.import_refs(
             b"refs/remotes/origin",
             {b"master": b"42d06bd4b77fed026b154d16493e5deab78f02ec"},
@@ -333,9 +333,9 @@ class RefsContainerTests:
         )
 
     def test_import_refs_name_prune(self):
-        self._refs[b"refs/remotes/origin/other"] = (
-            b"48d01bd4b77fed026b154d16493e5deab78f02ec"
-        )
+        self._refs[
+            b"refs/remotes/origin/other"
+        ] = b"48d01bd4b77fed026b154d16493e5deab78f02ec"
         self._refs.import_refs(
             b"refs/remotes/origin",
             {b"master": b"42d06bd4b77fed026b154d16493e5deab78f02ec"},
```

**Pull request merged**
