### PR TITLE
Add equality comparisons.

### PR DESCRIPTION
**Pull request by Julian**
Not sure this is the right implementation for subclasses but it seems like a start?

### CODE REVIEW

**Comment by jelmer** [comment]
The object store side of this looks reasonable to me. Can you submit that as a separate pull request?

Repositories are trickier - your change doesn't add a Repo.__eq__ method so no two Repo objects are going to be the same.

**Comment by jelmer** [comment]
Sorry, I missed the new method on BaseRepo. Just comparing refs and objects is sufficient as far as the tests are concerned. 

For proper comparison you would probably also want to check e.g. the reflog and the configuration of the repository - possibly the working tree. This is not likely to be very useful I think, and it will be unusably slow on any repository that isn't trivial in size. What do you need repository comparison for, is there perhaps a more efficient alternative?

**Comment by Julian** [comment]
Hrm. Understood. My use case is also for tests, I have my own objects with repo attributes and not being able to compare Repo objects means my own equality checks are awkward. I agree that comparing everything recursively inside the repository doesn't sound very useful.

**Comment by jelmer** [comment]
On Sun, Jul 03, 2016 at 08:22:44AM -0700, Julian Berman wrote:
> Hrm. Understood. My use case is also for tests, I have my own objects with repo attributes and not being able to compare Repo objects means my own equality checks are awkward. I agree that comparing everything recursively inside the repository doesn't sound very useful.

Possibly we could just add a test helper for this purpose?

Jelmer

**Pull request closed without merging**
