### PR TITLE
Allow passing abbrev to describe

### PR DESCRIPTION
**Pull request by nanonyme**
This provides ability for user to request full commit through API

### CODE REVIEW

**Comment by jelmer** [comment]
Thanks! Can you also add a test in dulwich/tests/test_porcelain.py ? (around line 2947)

**Review by jelmer — CHANGES_REQUESTED** [review]
See other comment

**Comment by nanonyme** [comment]
Force pushed to fix flake8 nit about extra newline.

**Comment by nanonyme** [comment]
It looks like docs is failing because it's running on Python 3.11 which is incompatible with pydoctor used.

**Pull request merged**
