### PR TITLE
Make Index support multiple IndexEntries for the same path by stage for merge conflict support

### PR DESCRIPTION
**Pull request by kevinhendricks**
With these changes in place dulwich master passes make check.

Hope something close to this can be integrated into dulwich master so that work on an external merge capability can continue.

### CODE REVIEW

**Comment by kevinhendricks** [comment]
I will reformat the code to pass flake8 tomorrow.

**Comment by kevinhendricks** [comment]
@jelmer 

My dulwich_merge repo now support diffs from working dir to index, index to tree, tree to tree, and tree to working dir.  And more importantly it now supports diff3merge, histogramdiff, ort (recursive) and resolve (non-recursive) tree/branch merging properly handling multiple lcas using the virtual commits approach used by git itself.  The current dulwich_merge repo fully passes the libgit2 merge-recursive set of tests and all code now passes flake8, and mypy and pass the dulwich test-suite.

I would like to present them to you as a series of pull requests, if you are interested:

1) expand dulwich diff support to working dir and etc (touching patch.py, index.py and procelain.py)

2) basic 3 way merge building blocks: myersdiff.py, histogramdiff.py, and diff3merge.py (with tests)

3) a greatly improved graph.py find_lcas routine that uses priority queues and commit-time information to become much much more efficient for "can fast forward" (along with a revised test_graph.py)

4) merge.py and its associated support changes in porcelain.py

And as before, any code I write for dulwich can be relicensed to the license dulwich uses.  I will simply host the MIT/BSD license versions for other projects to use if desired on Sigil.

If interested in adding branch/tree merge support to dulwich and expanded diff support as a series of PRs please let me know.  

If not, if you could at least incorporate this index.py pull request (and maybe an even newer and improved graph.py  - see 3. above) into master, then dulwich_merge can can be released by Sigil as a separate dulwich "add-on" module until you decide when and if you want to add that capability to dulwich sometime down the road.  

All of the code is available for your inspection, testing, feedback, change requests, etc at:

https://github.com/Sigil-Ebook/dulwich_merge

Thank you for your time and consideration,

Kevin

**Comment by jelmer** [comment]
Thanks! Merged with some additional refactoring on top. The new code doesn't have any unit tests yet; I'll see if I can add some later.

**Comment by kevinhendricks** [comment]
Actually the new code is exercised by the merge tests if and when it is added.

Thank you!

**Comment by jelmer** [comment]
That's not a unit test though. :-)

**Comment by jelmer** [comment]
@kevinhendricks I would really appreciate pull requests to add the features you mention.

That said, the reason it's taken a while to merge your other changes is that they tend to be quite large and diverge significantly from the rest of Dulwich in terms of style and practices. For example, code without direct unit tests tends to regress and Dulwich tries really hard to provide a sensible API. Another example is that having the changes in a separate repository (with history unrelated to the main Dulwich repo) also makes it hard to see exactly what has changed or to merge it.

This makes it hard for me to merge these changes because they require a lot of time to review and understand, and then to provide feedback on (followed by improvements and more feedback) or adapt to the rest of Dulwich. I wish I had more time for Dulwich, but in practice this means it takes me a while to follow up to these large PRs. If you look at what gets merged into master, it tends to be PRs that.

I can try to document the expectations for Dulwich PRs better if that helps The thing that would help me is having contributions in PRs and having smaller PRs to review that already come with unit tests that verify what exactly they're changing in the behaviour. If it helps, I'm also happy to discuss new APIs / API changes up front in bug reports so we can agree on them before you start implementing.

If there's anything else I can do to help, let me know.

**Comment by jelmer** [comment]
FWIW I've tried to write down some recommendations for getting PRs here: https://jelmer.uk/pages/getting-your-prs-merged.html

Please propose your merge changes as a PR; I am really interested in getting that merged, and will try to provide respond quickly (rather than necessarily super in depth)

**Pull request merged**
