### PR TITLE
Fix typo in porcelain.push() docstring

### PR DESCRIPTION
**Pull request by fviolette**

### CODE REVIEW

**Comment by jelmer** [comment]
Any chance you can push this to the repo? GitHub currently indicates "unknown repository".

**Comment by fviolette** [comment]
I had to delete the repo - does this invalide the PR or to I can rebranch it somehow?

**Comment by jelmer** [comment]
Yeah, in invalidates the PR.

**Comment by fviolette** [comment]
No problem then, it can be closed.

**Pull request closed without merging**
