### PR TITLE
Parse user:passwords for HTTPGitClient

### PR DESCRIPTION
**Pull request by jsbain**
This solves #249, allowing get_transport_and_path to use http basic auth user:pass style urls, or to directly specify user/pass in a HTTPGitClient.

This works in porcelain as well (push, etc).

One possible issue: when using porcelain to push, using user:pass urls, the password will be displayed in the success /failure messages.  probably not a major issue if using the default outstream and errstream, but if logging is implemented, passwords would be displayed in the clear.  The solution might be to use client.base_url for httpgitclients, rather than remote_location.

### CODE REVIEW

**Comment by jelmer** [comment]
On Tue, Jan 05, 2016 at 03:59:08AM -0800, jsbain wrote:
> This solves #249, allowing get_transport_and_path to use http basic auth user:pass style urls, or to directly specify user/pass in a HTTPGitClient.
Thanks! Any chance you can add a test or two for this to dulwich/tests/test_client.py, just making sure that
the username and password in the URL end up in HTTPGitClient?

> This works in porcelain as well (push, etc).
> 
> One possible issue: when using porcelain to push, using user:pass urls, the password will be displayed in the success /failure messages.  probably not a major issue if using the default outstream and errstream, but if logging is implemented, passwords would be displayed in the clear.  The solution might be to use client.base_url for httpgitclients, rather than remote_location.

Adding GitClient.get_url() seems reasonable to me; we can then use that in error messages.

Jelmer

**Comment by mjmaenpaa** [comment]
So what's the status of this pull request, because I really need this functionality.

If only tests are needed, then I can write them. Adding GitClient.get_url is propably little more complicated if we want it to return meaningful urls with all clients. However I can do basic version which can be updated later to include more meaningful urls.

**Comment by jelmer** [comment]
I haven't heard from jsbain since January so any help getting this implemented would be great. I don't think we need a get_url() method just yet, but we probably want to make base_url private.

**Comment by mjmaenpaa** [comment]
It seems that I forgot to make pull request even though i wrote tests two weeks ago.

I wrote few tests for this that make sure that username and password end up in HttpGitClient when using get_transport_and_path. Additionally they make sure that init actually ends up calling HTTPPasswordMgrWithDefaultRealm.add_password.

I can make new pull request with just my tests or new pull request that includes both my tests and jsbain's changes rebased against master.

**Comment by jelmer** [comment]
On Wed, Jul 27, 2016 at 01:57:24PM -0700, mjmaenpaa wrote:
> It seems that I forgot to make pull request even though i wrote tests two weeks ago.
> 
> I wrote few tests for this that make sure that username and password end up in HttpGitClient when using get_transport_and_path. Additionally they make sure that init actually ends up calling HTTPPasswordMgrWithDefaultRealm.add_password.
> 
> I can make new pull request with just my tests or new pull request that includes both my tests and jsbain's changes rebased against master.
A pull request with both would be great. I've just merged your other
one.

**Comment by jelmer** [comment]
Superseded by #445

**Comment by jelmer** [comment]
On Wed, Jul 27, 2016 at 01:57:24PM -0700, mjmaenpaa wrote:
> It seems that I forgot to make pull request even though i wrote tests two weeks ago.
> 
> I wrote few tests for this that make sure that username and password end up in HttpGitClient when using get_transport_and_path. Additionally they make sure that init actually ends up calling HTTPPasswordMgrWithDefaultRealm.add_password.
> 
> I can make new pull request with just my tests or new pull request that includes both my tests and jsbain's changes rebased against master.

Thanks.

FWIW this is still on my todo list. I'm hoping to get to it sometime this week.

**Pull request closed without merging**
